image:
  name: docker/compose:1.23.2
  entrypoint: ["sh", "-c"]
variables:
  DOCKER_HOST: tcp://docker:2375
services:
  - docker:dind

# global *_script will overwrite by job defined *_script
before_script:
  - wget -qO- https://arp.to/@ci/scripts/before.sh | sh
after_script:
  - wget -qO- https://arp.to/@ci/scripts/after.sh | sh

container-image:
  stage: build
  only:
    - master
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest ${BUILD_OPTS} .
    - docker push  ${CI_REGISTRY_IMAGE}:latest
